# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=9)),
                ('source', models.CharField(max_length=30)),
                ('Destination', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'modified_at',
            },
        ),
        migrations.CreateModel(
            name='CargoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Transit', 'Transit'), ('Border', 'Border'), ('Damaged', 'Damaged'), ('Impounded', 'impounded')], max_length=30)),
                ('Laswt_location', models.CharField(max_length=30)),
                ('next_station', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='tracker.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('organisation', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='tracker.Customers'),
        ),
    ]
