# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160523_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargostate',
            old_name='Laswt_location',
            new_name='Last_location',
        ),
    ]
