# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160523_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='description',
            field=models.CharField(default='welcome', max_length=255),
            preserve_default=False,
        ),
    ]
